In [ ]:
import numpy as np
#i wihich array print 3 rows and 2 columns with empty values
np.empty((3, 2))


array([[6.85674137e-312, 7.50346312e+021],
       [6.85673040e-312, 6.85673040e-312],
       [5.43472210e-323, 3.45845952e-323]])

In [ ]:
# in which array print 0 to 15 with step 2
a=np.arange(0,15,2)
print(a)

[ 0  2  4  6  8 10 12 14]


In [ ]:
#linspace make linear space between 0 to 10 and total values is 5    

b=np.linspace(0,10,5)
print(b)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [ ]:
#if i want to get values in integer type
b=np.linspace(0,10,5 , dtype=np.int64)
print(b)

[ 0  2  5  7 10]


In [13]:
#sorting an array
c=np.array([3,4,2,3,2,4,2,34,5,5,6,7,8,8,9])
c.sort()
print(c)

[ 2  2  2  3  3  4  4  5  5  6  7  8  8  9 34]


In [15]:
#concatenate two arrays
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 5 6 7 8 9]


In [16]:
#2d concatenate
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b))
print(c)    

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
#if i want to check the dimension of array
print(c.ndim)   

2


In [19]:
#3dimensional array
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[5 6]
  [7 8]]]


In [ ]:
#if i want to check the shape of array
# 3 means 3 dimensions and (2,2) means 2 rows and 2 columns
print(a.shape)  

(3, 2, 2)


In [23]:
#reshape the array
a=np.array([1,2,3,4,5,6,7,8 ])
b=a.reshape(4,2)
print(b)    

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [28]:
# indexing and slicing
a=np.array([1,2,3,4,5,6,7,8 ])
print(a[0])  #print first element
print(a[1:5]) #print from index 1 to 4
print(a[:5])  #print from start to index 4
print(a[5:])  #print from index 5 to end
print(a[-1])  #print last element
print(a[-3:]) #print last 3 elements
print(a[::2]) #print step=2 elements
print(a[1::2]) #print from index 1 with step=2 elements
print(a[::-1]) #print reverse array
print(a[-2::-1]) #print from second last to start in reverse order


1
[2 3 4 5]
[1 2 3 4 5]
[6 7 8]
8
[6 7 8]
[1 3 5 7]
[2 4 6 8]
[8 7 6 5 4 3 2 1]
[7 6 5 4 3 2 1]
